path = src
cc = gcc

all:backend frontend
	@echo "Successful complilation!"

backend: ${path}/backend.c ${path}/backend.h
	${cc} ${path}/backend.c  -o backend
	@echo "Successful complilation of backend!"

frontend: ${path}/frontend.c ${path}/frontend.h
	${cc} ${path}/frontend.c  -o frontend
	@echo "Successful complilation of frontend!"

clean:
	rm backend frontend 
	@echo "Files deleted Successfully!"



