
frontend_files = ./frontend.h ./frontend.c 
backend_files = ./backend.h ./backend.c 


all: frontend backend

frontend:$(frontend_files)
	gcc ./frontend.c -o ./frontend 


backend:$(backend_files)
	gcc backend.c -o backend

clean: ./frontend ./backend
	rm -f ./frontend ./backend

