path = src
tmp_path = tmp
cc = gcc

all:backend frontend
	@echo "Successful complilation!"

backend: ${path}/backend.c  ${path}/backend.h ${path}/utils.h
	${cc} ${path}/backend.c  -o backend users_lib.o
	@echo "Successful complilation of backend!"

frontend: ${path}/frontend.c   ${path}/frontend.h ${path}/utils.h
	${cc} ${path}/frontend.c  -o frontend
	@echo "Successful complilation of frontend!"

clean:
	rm backend frontend ${tmp_path}/cli_* ${tmp_path}/fifo_server
	@echo "Files deleted Successfully!"



